name: build the news for linux

on:
  push:
    branches: [ master, main ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build and Package
    runs-on: ubuntu-latest
    container:
      image: fedora:42
      options: --privileged

    steps:
      - name: Install build dependencies
        run: |
          dnf -y update
          dnf -y install --skip-broken \
            cmake \
            make \
            gcc \
            gcc-c++ \
            git \
            qt6-qtbase-devel \
            qt6-qttools-devel \
            qt6-qtsvg-devel \
            qt6-qtmultimedia-devel \
            qt6-qtdeclarative-devel \
            qt6-qtquickcontrols2-devel \
            flatpak \
            flatpak-builder \
            desktop-file-utils \
            fuse \
            fuse3 \
            patchelf \
            wget \
            libnotify-devel \
            libnotify \
            glib2-devel \
            glib2 \
            ImageMagick \
            file

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build project
        run: |
          mkdir -p build
          cd build
          cmake ../src
          make -j$(nproc)

      - name: Prepare Flatpak manifest
        run: |
          # Create a .desktop file dynamically if it doesn't exist
          mkdir -p src/assets
          if [ ! -f src/assets/thenews.desktop ]; then
            cat > src/assets/thenews.desktop <<'DESKTOP_EOF'
          [Desktop Entry]
          Name=the news
          Exec=thenews
          Icon=thenews
          Type=Application
          Categories=Utility;
          DESKTOP_EOF
          fi

          # Create Flatpak manifest
          cat > com.weenie.thenews.yml <<'FLATPAK_EOF'
          app-id: com.weenie.thenews
          runtime: org.freedesktop.Platform
          runtime-version: '24.08'
          sdk: org.freedesktop.Sdk
          command: thenews
          finish-args:
            - --share=network
            - --socket=x11
            - --socket=wayland
            - --device=dri
            - --filesystem=home
          modules:
            - name: thenews
              buildsystem: simple
              build-commands:
                - install -Dm755 build/thenews /app/bin/thenews
                - install -Dm644 src/assets/thenews.png /app/share/icons/hicolor/256x256/apps/thenews.png
                - install -Dm644 src/assets/thenews.desktop /app/share/applications/com.weenie.thenews.desktop
              sources:
                - type: dir
                  path: .
          FLATPAK_EOF

      - name: Build Flatpak
        run: |
          # Add flathub remote
          flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
          
          # Install runtime and SDK
          flatpak install -y flathub org.freedesktop.Platform//24.08
          flatpak install -y flathub org.freedesktop.Sdk//24.08
          
          # Build Flatpak with --disable-rofiles-fuse to work in containers
          flatpak-builder --disable-rofiles-fuse --force-clean build-dir com.weenie.thenews.yml
          flatpak build-export repo build-dir
          flatpak build-bundle repo thenews.flatpak com.weenie.thenews

      - name: Build AppImage
        run: |
          APPDIR=AppDir
          mkdir -p $APPDIR/usr/bin
          mkdir -p $APPDIR/usr/share/applications
          mkdir -p $APPDIR/usr/share/icons/hicolor/256x256/apps

          # Copy binary
          cp build/thenews $APPDIR/usr/bin/

          # Resize icon to 256x256 and copy it
          convert src/assets/thenews.png -resize 256x256 $APPDIR/usr/share/icons/hicolor/256x256/apps/thenews.png

          # Create .desktop file automatically
          cat > $APPDIR/usr/share/applications/thenews.desktop <<'APPIMAGE_EOF'
          [Desktop Entry]
          Name=the news
          Exec=thenews
          Icon=thenews
          Type=Application
          Categories=Utility;
          APPIMAGE_EOF

          # Download linuxdeploy + Qt plugin
          wget -q https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
          wget -q https://github.com/linuxdeploy/linuxdeploy-plugin-qt/releases/download/continuous/linuxdeploy-plugin-qt-x86_64.AppImage
          chmod +x linuxdeploy-*.AppImage

          # Set Qt6 paths and environment
          export QT_SELECT=6
          export QML_SOURCES_PATHS=src
          export DISABLE_COPYRIGHT_FILES_DEPLOYMENT=1
          export NO_STRIP=1
          export QMAKE=/usr/bin/qmake-qt6
          
          # Build AppImage with verbose output
          ./linuxdeploy-x86_64.AppImage --appdir $APPDIR \
            -e build/thenews \
            -d $APPDIR/usr/share/applications/thenews.desktop \
            -i $APPDIR/usr/share/icons/hicolor/256x256/apps/thenews.png \
            --plugin qt \
            --output appimage || true
          
          # If linuxdeploy fails due to strip errors, try without Qt plugin
          if [ ! -f *.AppImage ]; then
            echo "Retrying without strip..."
            rm -rf $APPDIR
            mkdir -p $APPDIR/usr/bin
            mkdir -p $APPDIR/usr/share/applications
            mkdir -p $APPDIR/usr/share/icons/hicolor/256x256/apps
            cp build/thenews $APPDIR/usr/bin/
            convert src/assets/thenews.png -resize 256x256 $APPDIR/usr/share/icons/hicolor/256x256/apps/thenews.png
            cat > $APPDIR/usr/share/applications/thenews.desktop <<'RETRY_EOF'
          [Desktop Entry]
          Name=the news
          Exec=thenews
          Icon=thenews
          Type=Application
          Categories=Utility;
          RETRY_EOF
            
            # Manually copy Qt plugins since linuxdeploy-plugin-qt might fail
            mkdir -p $APPDIR/usr/plugins/platforms
            cp /usr/lib64/qt6/plugins/platforms/*.so $APPDIR/usr/plugins/platforms/ || true
            
            ./linuxdeploy-x86_64.AppImage --appdir $APPDIR \
              -e build/thenews \
              -d $APPDIR/usr/share/applications/thenews.desktop \
              -i $APPDIR/usr/share/icons/hicolor/256x256/apps/thenews.png \
              --output appimage
          fi
          
          # Verify Qt plugins were bundled
          echo "Checking bundled Qt plugins:"
          find $APPDIR -name "*.so" | grep -i platform || echo "WARNING: No platform plugins found!"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: thenews-linux
          path: |
            ./*.flatpak
            ./*.AppImage