name: build the news for linux

on:
  push:
    branches: [ master, main ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build and Package
    runs-on: ubuntu-latest
    container:
      image: fedora:41
      options: --privileged

    steps:
      - name: Install build dependencies
        run: |
          dnf -y update
          dnf -y install --skip-broken \
            cmake \
            make \
            gcc \
            gcc-c++ \
            git \
            qt6-qtbase-devel \
            qt6-qttools-devel \
            qt6-qtsvg-devel \
            qt6-qtmultimedia-devel \
            qt6-qtdeclarative-devel \
            qt6-qtquickcontrols2-devel \
            qt6-qtwayland \
            flatpak \
            flatpak-builder \
            desktop-file-utils \
            fuse \
            fuse3 \
            patchelf \
            wget \
            libnotify-devel \
            libnotify \
            glib2-devel \
            glib2 \
            ImageMagick \
            file

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build project
        run: |
          mkdir -p build
          cd build
          cmake ../src
          make -j$(nproc)

      - name: Prepare Flatpak manifest
        run: |
          # Create a .desktop file dynamically if it doesn't exist
          mkdir -p src/assets
          if [ ! -f src/assets/thenews.desktop ]; then
            cat > src/assets/thenews.desktop <<'DESKTOP_EOF'
          [Desktop Entry]
          Name=the news
          Exec=thenews
          Icon=com.weenie.thenews
          Type=Application
          Categories=Utility;
          DESKTOP_EOF
          fi

          # Create Flatpak manifest with Qt6 runtime
          cat > com.weenie.thenews.yml <<'FLATPAK_EOF'
          app-id: com.weenie.thenews
          runtime: org.kde.Platform
          runtime-version: '6.8'
          sdk: org.kde.Sdk
          command: thenews
          finish-args:
            - --share=network
            - --socket=x11
            - --socket=wayland
            - --device=dri
            - --filesystem=home
          modules:
            - name: thenews
              buildsystem: simple
              build-commands:
                - install -Dm755 build/thenews /app/bin/thenews
                - install -Dm644 src/assets/thenews.png /app/share/icons/hicolor/256x256/apps/com.weenie.thenews.png
                - install -Dm644 src/assets/thenews.desktop /app/share/applications/com.weenie.thenews.desktop
                - desktop-file-edit --set-icon=com.weenie.thenews /app/share/applications/com.weenie.thenews.desktop
              sources:
                - type: dir
                  path: .
          FLATPAK_EOF

      - name: Build Flatpak
        run: |
          # Add flathub remote
          flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
          
          # Install KDE runtime and SDK with Qt6
          flatpak install -y flathub org.kde.Platform//6.8
          flatpak install -y flathub org.kde.Sdk//6.8
          
          # Build Flatpak INSIDE the SDK to ensure Qt version compatibility
          flatpak-builder --disable-rofiles-fuse --force-clean build-dir com.weenie.thenews.yml
          
          # Rebuild the app inside the flatpak environment to match Qt versions
          flatpak build build-dir bash -c "cd /run/build/thenews && rm -rf build && mkdir build && cd build && cmake ../src && make -j$(nproc) && install -Dm755 thenews /app/bin/thenews"
          
          flatpak build-export repo build-dir
          flatpak build-bundle repo thenews.flatpak com.weenie.thenews

      - name: Build AppImage
        run: |
          APPDIR=AppDir
          rm -rf $APPDIR
          mkdir -p $APPDIR/usr/bin
          mkdir -p $APPDIR/usr/share/applications
          mkdir -p $APPDIR/usr/share/icons/hicolor/256x256/apps

          # Copy binary
          cp build/thenews $APPDIR/usr/bin/

          # Resize icon to 256x256 and copy it
          magick src/assets/thenews.png -resize 256x256 $APPDIR/usr/share/icons/hicolor/256x256/apps/thenews.png

          # Create .desktop file
          cat > $APPDIR/usr/share/applications/thenews.desktop <<'APPIMAGE_EOF'
          [Desktop Entry]
          Name=the news
          Exec=thenews
          Icon=thenews
          Type=Application
          Categories=Utility;
          APPIMAGE_EOF

          # Download linuxdeploy and Qt plugin
          wget -q https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
          wget -q https://github.com/linuxdeploy/linuxdeploy-plugin-qt/releases/download/continuous/linuxdeploy-plugin-qt-x86_64.AppImage
          chmod +x linuxdeploy-*.AppImage

          # Extract to avoid FUSE issues
          ./linuxdeploy-x86_64.AppImage --appimage-extract
          mv squashfs-root linuxdeploy-squashfs
          ./linuxdeploy-plugin-qt-x86_64.AppImage --appimage-extract
          mv squashfs-root linuxdeploy-plugin-qt-squashfs
          
          # Set environment variables for Qt6
          export QMAKE=/usr/bin/qmake-qt6
          export QT_SELECT=6
          export QML_SOURCES_PATHS=src
          export DISABLE_COPYRIGHT_FILES_DEPLOYMENT=1
          export LD_LIBRARY_PATH=/usr/lib64/qt6:$LD_LIBRARY_PATH
          
          # Build AppImage
          ./linuxdeploy-squashfs/AppRun --appdir $APPDIR \
            -e build/thenews \
            -d $APPDIR/usr/share/applications/thenews.desktop \
            -i $APPDIR/usr/share/icons/hicolor/256x256/apps/thenews.png \
            --plugin qt \
            --output appimage
          
          # If that fails, do it manually
          if [ ! -f *.AppImage ]; then
            echo "=== Building AppImage manually with full Qt6 support ==="
            
            # Deploy dependencies
            ./linuxdeploy-squashfs/AppRun --appdir $APPDIR \
              -e build/thenews \
              -d $APPDIR/usr/share/applications/thenews.desktop \
              -i $APPDIR/usr/share/icons/hicolor/256x256/apps/thenews.png
            
            # Manually copy Qt6 plugins
            mkdir -p $APPDIR/usr/plugins
            cp -r /usr/lib64/qt6/plugins/* $APPDIR/usr/plugins/ 2>/dev/null || true
            
            # Copy Wayland libraries
            cp /usr/lib64/libQt6WaylandClient.so.6* $APPDIR/usr/lib/ 2>/dev/null || true
            cp /usr/lib64/libQt6WaylandEglClientHwIntegration.so.6* $APPDIR/usr/lib/ 2>/dev/null || true
            cp /usr/lib64/libwayland-client.so* $APPDIR/usr/lib/ 2>/dev/null || true
            cp /usr/lib64/libwayland-cursor.so* $APPDIR/usr/lib/ 2>/dev/null || true
            cp /usr/lib64/libwayland-egl.so* $APPDIR/usr/lib/ 2>/dev/null || true
            
            # Create qt.conf
            cat > $APPDIR/usr/bin/qt.conf <<'QTCONF_EOF'
          [Paths]
          Plugins = ../plugins
          QTCONF_EOF
            
            # Create custom AppRun with proper environment
            cat > $APPDIR/AppRun <<'APPRUN_EOF'
          #!/bin/bash
          APPDIR="$(dirname "$(readlink -f "$0")")"
          
          export LD_LIBRARY_PATH="$APPDIR/usr/lib:$LD_LIBRARY_PATH"
          export QT_PLUGIN_PATH="$APPDIR/usr/plugins"
          export QT_QPA_PLATFORM_PLUGIN_PATH="$APPDIR/usr/plugins/platforms"
          
          # Try Wayland first, fallback to XCB
          if [ -n "$WAYLAND_DISPLAY" ]; then
            export QT_QPA_PLATFORM="wayland;xcb"
          else
            export QT_QPA_PLATFORM="xcb"
          fi
          
          exec "$APPDIR/usr/bin/thenews" "$@"
          APPRUN_EOF
            chmod +x $APPDIR/AppRun
            
            # Build AppImage
            ARCH=x86_64 ./linuxdeploy-squashfs/AppRun --appdir $APPDIR --output appimage
          fi
          
          # Verify
          echo "=== Verification ==="
          echo "Platform plugins:"
          find $APPDIR -path "*/plugins/platforms/*.so" 2>/dev/null | head -5
          echo "Generated AppImages:"
          ls -lh *.AppImage 2>/dev/null || echo "ERROR: No AppImage generated"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: thenews-linux
          path: |
            ./*.flatpak
            ./*.AppImage